a = input('Digite algo: ')
print(f'O tipo primitivo é {type(a)}')
print(f'Só tem espaços?{a.isspace()}')
print(f'É um número?{a.isnumeric()}')
print(f'É alfabético?{a.isalpha()}')
print(f'É alfanumerico?{a.isalnum()}')
print(f'Ele está em maiúsculas?{a.isupper()}')
print(f'Ele está em minúsculas?{a.islower()}')
print(f'Ele está capitalizado?{a.istitle()}')